Allow configuring the default log channel for events
nuwber/rabbitevents pull request #102
Opened 2022-11-15 18:14 UTC by morloderex

Hey.

This is a very simple request which allows us to specify the logging channel for the listen command.

Instead of relaying on the default logging channel i would like it to only log to one specific channel that is different from the application itself

2022-11-16 09:41 UTC, masterjus requested changes

2022-11-16 09:41 UTC, masterjus commented on src/RabbitEvents/Listener/Commands/ListenCommand.php
> +                Arr::get($config, 'logging.channel', null),
update config.php and documentation please

2022-11-16 09:41 UTC, masterjus commented on src/RabbitEvents/Listener/Commands/Log/General.php
> +    public function __construct(protected Container $app, protected string $defaultLogLevel = 'info', protected ?string $channel = null)
Looks like the variable is not `defaultLogLevel` but `logLevel`

2022-11-16 11:46 UTC, morloderex commented on src/RabbitEvents/Listener/Commands/Log/General.php
> +    public function __construct(protected Container $app, protected string $defaultLogLevel = 'info', protected ?string $channel = null)
@masterjus using `defaultLogLevel` the value comes from `rabbitevents.logging.channel` configuration value, meaning it will become the `default` used within this class? I can change it to `logLevel` if you think it's clearer.

2022-11-16 15:24 UTC, morloderex commented
@masterjus I have added config value. And updated documentation. Anything else you want me to look at?

2022-11-17 13:45 UTC, masterjus commented on src/RabbitEvents/Listener/Commands/Log/General.php
> +    public function __construct(protected Container $app, protected string $defaultLogLevel = 'info', protected ?string $channel = null)
So this class will always be instantiated with defaultLogLevel? In terms of this class it something that was passed outside, I think.

2022-11-17 16:07 UTC, morloderex commented on src/RabbitEvents/Listener/Commands/Log/General.php
> +    public function __construct(protected Container $app, protected string $defaultLogLevel = 'info', protected ?string $channel = null)
@masterjus As it's currently built the parameter for defaultLogLevel will always get passed it assuming use only within the Worker instance.

At that point it will become default within this class.

I am not very keen on parameter naming  here i have no objections on changing the naming if you want me to do that fine.

2022-11-18 08:53 UTC, masterjus approved these changes

2022-11-18 08:54 UTC, merged